#!/bin/bash

source portal-app-variable.yml

PORTALAPPNAME=portal-app-1.2.0
PORTALAPPDOWNLOADLINK=https://nextcloud.paas-ta.org/index.php/s/Q5fRjHYBxmWrpaq/download

#########################################
# Portal Component Folder Name
PORTAL-API=portal-api-2.4.0
PORTAL-COMMON-API=portal-common-api-2.2.0
PORTAL-GATEWAY=portal-gateway-2.1.0
PORTAL-LOG-API=portal-log-api-2.2.0
PORTAL-REGISTRATION=portal-registration-2.1.0
PORTAL-STORAGE-API=portal-storage-api-2.2.0
PORTAL-WEB-ADMIN=portal-web-admin-2.3.0
PORTAL-WEB-USER=portal-web-user-2.3.1
PORTAL-SSH=portal-ssh-1.0.0

#########################################

CURRENTDIRCTORY=$(pwd)

mkdir $PORTAL_APP_WORKING_DIRECTORY -p
cd $PORTAL_APP_WORKING_DIRECTORY
# portal-app download
## portal-app zip downloaded check
if [ -e $PORTALAPPNAME.zip ]; then
        echo "portal-app zip file exists - download skip"
else
        echo "portal-app zip file not exists - download zip file "
        ## portal-app wget download
        wget --content-disposition $PORTALAPPDOWNLOADLINK
fi

#########################################
# portal-app unzip
if [ -d $PORTALAPPNAME ]; then
        echo "portal-app folder exists - delete folder"
        ## existing portal-app directory delete
        ll | grep "$PORTALAPPNAME" | grep ^d | awk '{print $NF}' | xargs rm -rf
fi
## portal-app unzip
echo "portal-app unzip"
unzip $PORTALAPPNAME.zip

#########################################
#config change

cd $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/

find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-API -type f | xargs sed -i -e 's/<DOMAIN>/'${DOMAIN}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<DOMAIN>/'${DOMAIN}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-GATEWAY -type f | xargs sed -i -e 's/<DOMAIN>/'${DOMAIN}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-LOG-API -type f | xargs sed -i -e 's/<DOMAIN>/'${DOMAIN}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-REGISTRATION -type f | xargs sed -i -e 's/<DOMAIN>/'${DOMAIN}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-STORAGE-API -type f | xargs sed -i -e 's/<DOMAIN>/'${DOMAIN}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-WEB-ADMIN -type f | xargs sed -i -e 's/<DOMAIN>/'${DOMAIN}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-WEB-USER/config -type f | xargs sed -i -e 's/<DOMAIN>/'${DOMAIN}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-API -type f | xargs sed -i -e 's/<CF_USER_ADMIN_USERNAME>/'${CF_USER_ADMIN_USERNAME}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-LOG-API -type f | xargs sed -i -e 's/<CF_USER_ADMIN_USERNAME>/'${CF_USER_ADMIN_USERNAME}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-API -type f | xargs sed -i -e 's/<CF_USER_ADMIN_PASSWORD>/'${CF_USER_ADMIN_PASSWORD}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-LOG-API -type f | xargs sed -i -e 's/<CF_USER_ADMIN_PASSWORD>/'${CF_USER_ADMIN_PASSWORD}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-API -type f | xargs sed -i -e 's/<UAA_CLIENT_ID>/'${UAA_CLIENT_ID}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-LOG-API -type f | xargs sed -i -e 's/<UAA_CLIENT_ID>/'${UAA_CLIENT_ID}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-API -type f | xargs sed -i -e 's/<UAA_CLIENT_SECRET>/'${UAA_CLIENT_SECRET}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-LOG-API -type f | xargs sed -i -e 's/<UAA_CLIENT_SECRET>/'${UAA_CLIENT_SECRET}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-API -type f | xargs sed -i -e 's/<UAA_ADMIN_CLIENT_ID>/'${UAA_ADMIN_CLIENT_ID}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-LOG-API -type f | xargs sed -i -e 's/<UAA_ADMIN_CLIENT_ID>/'${UAA_ADMIN_CLIENT_ID}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-API -type f | xargs sed -i -e 's/<UAA_ADMIN_CLIENT_SECRET>/'${UAA_ADMIN_CLIENT_SECRET}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-LOG-API -type f | xargs sed -i -e 's/<UAA_ADMIN_CLIENT_SECRET>/'${UAA_ADMIN_CLIENT_SECRET}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-API -type f | xargs sed -i -e 's/<UAA_LOGIN_CLIENT_ID>/'${UAA_LOGIN_CLIENT_ID}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-LOG-API -type f | xargs sed -i -e 's/<UAA_LOGIN_CLIENT_ID>/'${UAA_LOGIN_CLIENT_ID}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-API -type f | xargs sed -i -e 's/<UAA_LOGIN_CLIENT_SECRET>/'${UAA_LOGIN_CLIENT_SECRET}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-LOG-API -type f | xargs sed -i -e 's/<UAA_LOGIN_CLIENT_SECRET>/'${UAA_LOGIN_CLIENT_SECRET}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<PORTAL_DB_IP>/'${PORTAL_DB_IP}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-WEB-ADMIN -type f | xargs sed -i -e 's/<PORTAL_DB_IP>/'${PORTAL_DB_IP}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<PORTAL_DB_PORT>/'${PORTAL_DB_PORT}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-WEB-ADMIN -type f | xargs sed -i -e 's/<PORTAL_DB_PORT>/'${PORTAL_DB_PORT}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<PORTAL_DB_USER_PASSWORD>/'${PORTAL_DB_USER_PASSWORD}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-WEB-ADMIN -type f | xargs sed -i -e 's/<PORTAL_DB_USER_PASSWORD>/'${PORTAL_DB_USER_PASSWORD}'/g'

# PORTAL-API
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-API -type f | xargs sed -i -e 's/<ABACUS_URL>/'${ABACUS_URL}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-API -type f | xargs sed -i -e 's/<MONITORING_API_URL>/'${MONITORING_API_URL}'/g'

# PORTAL-COMMON-API
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<PAAS-TA_DB_DRIVER>/'${PAASTA_DB_DRIVER}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<PAAS-TA_DATABASE>/'${PAASTA_DATABASE}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<PAAS-TA_DB_IP>/'${PAASTA_DB_IP}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<PAAS-TA_DB_PORT>/'${PAASTA_DB_PORT}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<CC_DB_NAME>/'${CC_DB_NAME}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<CC_DB_USER_NAME>/'${CC_DB_USER_NAME}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<CC_DB_USER_PASSWORD>/'${CC_DB_USER_PASSWORD}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<UAA_DB_NAME>/'${UAA_DB_NAME}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<UAA_DB_USER_NAME>/'${UAA_DB_USER_NAME}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<UAA_DB_USER_PASSWORD>/'${UAA_DB_USER_PASSWORD}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<MAIL_SMTP_HOST>/'${MAIL_SMTP_HOST}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<MAIL_SMTP_PORT>/'${MAIL_SMTP_PORT}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<MAIL_SMTP_USERNAME>/'${MAIL_SMTP_USERNAME}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<MAIL_SMTP_PASSWORD>/'${MAIL_SMTP_PASSWORD}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<MAIL_SMTP_USEREMAIL>/'${MAIL_SMTP_USEREMAIL}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-COMMON-API -type f | xargs sed -i -e 's/<MAIL_SMTP_PROPERTIES_AUTHURL>/'${MAIL_SMTP_PROPERTIES_AUTHURL}'/g'

# PORTAL-STORAGE-API
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-STORAGE-API -type f | xargs sed -i -e 's/<OBJECTSTORAGE_TENANTNAME>/'${OBJECTSTORAGE_TENANTNAME}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-STORAGE-API -type f | xargs sed -i -e 's/<OBJECTSTORAGE_USERNAME>/'${OBJECTSTORAGE_USERNAME}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-STORAGE-API -type f | xargs sed -i -e 's/<OBJECTSTORAGE_PASSWORD>/'${OBJECTSTORAGE_PASSWORD}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-STORAGE-API -type f | xargs sed -i -e 's/<OBJECTSTORAGE_IP>/'${OBJECTSTORAGE_IP}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-STORAGE-API -type f | xargs sed -i -e 's/<OBJECTSTORAGE_PORT>/'${OBJECTSTORAGE_PORT}'/g'

# PORTAL-WEBUSER
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-WEB-USER/config -type f | xargs sed -i -e 's/<UAAC_PORTAL_CLIENT_ID>/'${UAAC_PORTAL_CLIENT_ID}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-WEB-USER/config -type f | xargs sed -i -e 's/<UAAC_PORTAL_CLIENT_SECRET>/'${UAAC_PORTAL_CLIENT_SECRET}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-WEB-USER/config -type f | xargs sed -i -e 's/<USER_APP_SIZE_MB>/'${USER_APP_SIZE_MB}'/g'
find $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-WEB-USER/config -type f | xargs sed -i -e 's/<MONITORING_ENABLE>/'${MONITORING_ENABLE}'/g'

#cd portal-web-user-2.3.1/config
sh $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/$PORTAL-WEB-USER/applyChangeConfig.sh
#cd ../../

#SECURITY GROUP
find . -name $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/portal-rule.json -type f | xargs sed -i -e 's/<PORTAL_DB_IP>/'${PORTAL_DB_IP}'/g'
find . -name $PORTAL_APP_WORKING_DIRECTORY/$PORTALAPPNAME/portal-rule.json -type f | xargs sed -i -e 's/<PAAS-TA_DB_IP>/'${PAASTA_DB_IP}'/g'

